### PR TITLE
Allow user to specify port for runjs websocket server.

### PR DESCRIPTION
**Pull request by MikeiLL**
In case, perhaps serving html page from another http.server with default port.

### CODE REVIEW

**Comment by MikeiLL** [comment]
By the way. Nice little server, sir! As usual. You are on fire.

**Comment by Rosuav** [comment]
If I make it any more complex, I'll use argparse properly, but this is fine for now.

**Comment by MikeiLL** [comment]
> If I make it any more complex, I'll use argparse properly, but this is fine for now.

You mean like with an [ArgumentParser](https://docs.python.org/3/library/argparse.html#adding-arguments)?

**Comment by Rosuav** [comment]
Exactly. At the moment, there's just one mandatory positional and one optional flag, but if there's anything more, I'll use that.

**Pull request merged**
